import * as fs from 'fs';
import * as path from 'path';
import { KnowledgeGraphResult } from './cp1_build_graph';

export interface ArchitectureSummary {
    overview: string;
    languages: string[];
    fileCount: number;
    entityCount: number;
    entryPoints: string[];
    coreModules: { name: string; reason: string }[];
    dependencies: { internal: number; external: number };
    complexityNote: string;
    gitNote: string;
    markdownReport: string;
}

/**
 * CP2: Generate a structured text summary of the codebase architecture.
 * This is the text that would be fed to an LLM as context.
 */
export function runCheckpoint2(
    workspacePath: string,
    graph: KnowledgeGraphResult,
    analysisDir: string
): ArchitectureSummary {

    // Load L1 manifest for languages & frameworks
    const l1Path = path.join(workspacePath, '.ail', 'layer1', 'meta-data.json');
    const l1 = fs.existsSync(l1Path) ? JSON.parse(fs.readFileSync(l1Path, 'utf-8')) : {} as Record<string, unknown>;

    // Load L2 manifest for entity/complexity stats
    const l2Path = path.join(workspacePath, '.ail', 'layer2', 'meta-data.json');
    const l2 = fs.existsSync(l2Path) ? JSON.parse(fs.readFileSync(l2Path, 'utf-8')) : {} as Record<string, unknown>;

    // Load L3 manifest for git stats
    const l3Path = path.join(workspacePath, '.ail', 'layer3', 'meta-data.json');
    const l3 = fs.existsSync(l3Path) ? JSON.parse(fs.readFileSync(l3Path, 'utf-8')) : {} as Record<string, unknown>;

    const workspaceName = path.basename(workspacePath);
    const languages: string[] = (l1 as any)?.languages?.detected?.map((d: any) => d.language) || [];
    const fileCount = graph.stats.nodesByType['file'] || 0;
    const entityCount = (l2 as any)?.summary?.totalEntities || 0;
    const entryPoints: string[] = (l1 as any)?.entryPoints?.entryPoints?.map((ep: any) => ep.file) || [];
    const externalDeps: string[] = (l2 as any)?.imports?.externalDeps || [];
    const complexFunctionCount = (l2 as any)?.summary?.complexFunctionCount || 0;
    const avgComplexity = (l2 as any)?.summary?.avgComplexity || 0;
    const totalCommits = (l3 as any)?.summary?.totalCommits || 0;
    const totalContributors = (l3 as any)?.summary?.totalContributors || 0;
    const hotFileCount = (l3 as any)?.summary?.hotFileCount || 0;

    // Find core modules: files with most incoming edges (most depended upon)
    const incomingCount = new Map<string, number>();
    for (const edge of graph.edges) {
        if (edge.type === 'imports' || edge.type === 'calls') {
            incomingCount.set(edge.target, (incomingCount.get(edge.target) || 0) + edge.weight);
        }
    }
    const coreModules = Array.from(incomingCount.entries())
        .sort(([, a], [, b]) => b - a)
        .slice(0, 10)
        .map(([name, count]) => ({
            name: name.replace('file::', ''),
            reason: `referenced ${count} times`,
        }));

    // Build the complexity note
    const complexityNote = complexFunctionCount > 0
        ? `⚠ ${complexFunctionCount} functions have cyclomatic complexity > 10 (avg: ${avgComplexity}). Consider refactoring.`
        : `All functions have manageable complexity (avg: ${avgComplexity}).`;

    // Git note
    const gitNote = totalCommits > 0
        ? `${totalCommits} commits by ${totalContributors} contributors. ${hotFileCount} files are actively churning.`
        : 'No git history available.';

    // Build overview
    const overview = `${workspaceName} is a ${languages.join('/')} project with ${fileCount} source files and ${entityCount} code entities.`;

    // Generate markdown report
    const md = [
        `# Architecture Summary — ${workspaceName}`,
        '',
        `> Auto-generated by AIL on ${new Date().toISOString().slice(0, 10)}`,
        '',
        '## Overview',
        overview,
        '',
        '## Languages',
        languages.map(l => `- ${l}`).join('\n'),
        '',
        '## Entry Points',
        entryPoints.length > 0 ? entryPoints.map(ep => `- \`${ep}\``).join('\n') : '_No entry points detected_',
        '',
        '## Core Modules (Most Referenced)',
        coreModules.map(m => `- \`${m.name}\` — ${m.reason}`).join('\n'),
        '',
        '## Dependencies',
        `- **Internal imports**: ${graph.stats.edgesByType['imports'] || 0} edges`,
        `- **External packages**: ${externalDeps.length} (${externalDeps.slice(0, 10).join(', ')}${externalDeps.length > 10 ? '...' : ''})`,
        '',
        '## Complexity',
        complexityNote,
        '',
        '## Git History',
        gitNote,
        '',
        '## Knowledge Graph',
        `- **${graph.stats.totalNodes}** nodes (${Object.entries(graph.stats.nodesByType).map(([k, v]) => `${v} ${k}s`).join(', ')})`,
        `- **${graph.stats.totalEdges}** edges (${Object.entries(graph.stats.edgesByType).map(([k, v]) => `${v} ${k}`).join(', ')})`,
    ].join('\n');

    const summary: ArchitectureSummary = {
        overview,
        languages,
        fileCount,
        entityCount,
        entryPoints,
        coreModules,
        dependencies: {
            internal: graph.stats.edgesByType['imports'] || 0,
            external: externalDeps.length,
        },
        complexityNote,
        gitNote,
        markdownReport: md,
    };

    const jsonPath = path.join(analysisDir, 'summary.json');
    fs.writeFileSync(jsonPath, JSON.stringify(summary, null, 2));

    const mdPath = path.join(analysisDir, 'architecture_summary.md');
    fs.writeFileSync(mdPath, md);

    console.log(`AIL L4-CP2 | Architecture summary generated (${md.length} chars)`);
    return summary;
}
