import * as fs from 'fs';
import * as path from 'path';
import { KnowledgeGraphResult } from './cp1_build_graph';

export interface ArchitectureSummary {
    overview: string;
    languages: string[];
    fileCount: number;
    entityCount: number;
    entryPoints: string[];
    coreModules: { name: string; reason: string }[];
    riskHotspots: { name: string; file: string; riskScore: number; complexity: number; churn: number; level: string }[];
    coupledPairs: { fileA: string; fileB: string; strength: number }[];
    busFactor: { file: string; contributors: number }[];
    dependencies: { internal: number; external: number };
    markdownReport: string;
}

/**
 * CP2: Generate an actionable architecture summary with risk findings.
 */
export function runCheckpoint2(
    workspacePath: string,
    graph: KnowledgeGraphResult,
    analysisDir: string
): ArchitectureSummary {

    // Load L1 manifest for languages & frameworks
    const l1Path = path.join(workspacePath, '.ail', 'layer1', 'meta-data.json');
    const l1 = fs.existsSync(l1Path) ? JSON.parse(fs.readFileSync(l1Path, 'utf-8')) : {} as Record<string, unknown>;

    // Load L2 manifest for entity/complexity stats
    const l2Path = path.join(workspacePath, '.ail', 'layer2', 'meta-data.json');
    const l2 = fs.existsSync(l2Path) ? JSON.parse(fs.readFileSync(l2Path, 'utf-8')) : {} as Record<string, unknown>;

    // Load L3 manifest for git stats
    const l3Path = path.join(workspacePath, '.ail', 'layer3', 'meta-data.json');
    const l3 = fs.existsSync(l3Path) ? JSON.parse(fs.readFileSync(l3Path, 'utf-8')) : {} as Record<string, unknown>;

    const workspaceName = path.basename(workspacePath);
    const languages: string[] = (l1 as any)?.languages?.detected?.map((d: any) => d.language) || [];
    const fileCount = graph.stats.nodesByType['file'] || 0;
    const entityCount = (l2 as any)?.summary?.totalEntities || 0;
    const entryPoints: string[] = (l1 as any)?.entryPoints?.entryPoints?.map((ep: any) => ep.file) || [];
    const externalDeps: string[] = (l2 as any)?.imports?.externalDeps || [];

    // Find core modules: files with most incoming edges
    const incomingCount = new Map<string, number>();
    for (const edge of graph.edges) {
        if (edge.type === 'imports' || edge.type === 'calls') {
            incomingCount.set(edge.target, (incomingCount.get(edge.target) || 0) + edge.weight);
        }
    }
    const coreModules = Array.from(incomingCount.entries())
        .sort(([, a], [, b]) => b - a)
        .slice(0, 10)
        .map(([name, count]) => ({
            name: name.replace('file::', ''),
            reason: 'referenced ' + count + ' times',
        }));

    // Risk Hotspots (from RPI scores)
    const riskHotspots = graph.nodes
        .filter(n => (n.type === 'function' || n.type === 'method') && typeof n.metadata.riskScore === 'number')
        .sort((a, b) => (b.metadata.riskScore as number) - (a.metadata.riskScore as number))
        .slice(0, 15)
        .map(n => ({
            name: n.name,
            file: n.file || '',
            riskScore: n.metadata.riskScore as number,
            complexity: (n.metadata.complexity as number) || 0,
            churn: (n.metadata.fileChurn as number) || 0,
            level: n.metadata.riskLevel as string,
        }));

    // Co-change coupling pairs
    const coChangePath = path.join(workspacePath, '.ail', 'layer3', 'analysis', 'co_change.json');
    let coupledPairs: { fileA: string; fileB: string; strength: number }[] = [];
    if (fs.existsSync(coChangePath)) {
        const coData = JSON.parse(fs.readFileSync(coChangePath, 'utf-8'));
        coupledPairs = (coData.stronglyCoupled || []).slice(0, 10).map((p: any) => ({
            fileA: p.fileA,
            fileB: p.fileB,
            strength: p.couplingStrength,
        }));
    }

    // Blast radius stats
    const blastPath = path.join(workspacePath, '.ail', 'layer3', 'analysis', 'blast_radius.json');
    let avgBlast = 0;
    let maxBlastCommit: any = null;
    if (fs.existsSync(blastPath)) {
        const blastData = JSON.parse(fs.readFileSync(blastPath, 'utf-8'));
        avgBlast = blastData.avgBlastRadius || 0;
        maxBlastCommit = blastData.maxBlastRadius || null;
    }

    const busFactor: { file: string; contributors: number }[] = [];
    const overview = workspaceName + ' is a ' + languages.join('/') + ' project with ' + fileCount + ' source files and ' + entityCount + ' code entities.';

    // Generate actionable markdown report
    const lines: string[] = [];
    lines.push('# Architecture Intelligence - ' + workspaceName);
    lines.push('');
    lines.push('> Auto-generated by AIL on ' + new Date().toISOString().slice(0, 10));
    lines.push('');
    lines.push('## Overview');
    lines.push(overview);
    lines.push('');
    lines.push('## Languages');
    for (const lang of languages) { lines.push('- ' + lang); }
    lines.push('');

    // Risk hotspots section
    if (riskHotspots.length > 0) {
        const criticalCount = riskHotspots.filter(r => r.level === 'critical').length;
        const highCount = riskHotspots.filter(r => r.level === 'high').length;
        lines.push('## Risk Hotspots');
        if (criticalCount > 0 || highCount > 0) {
            lines.push(criticalCount + ' CRITICAL and ' + highCount + ' HIGH risk functions detected:');
        }
        lines.push('');
        for (const h of riskHotspots.slice(0, 10)) {
            const tag = h.level === 'critical' ? '[CRITICAL]' : h.level === 'high' ? '[HIGH]' : h.level === 'medium' ? '[MEDIUM]' : '[LOW]';
            lines.push(tag + ' ' + h.name + ' in ' + path.basename(h.file) + ' - RPI: ' + h.riskScore.toFixed(2) + ' (complexity:' + h.complexity + ', churn:' + h.churn + ')');
        }
        lines.push('');
    }

    // Coupling section
    if (coupledPairs.length > 0) {
        lines.push('## Tightly Coupled Files');
        lines.push('These file pairs change together suspiciously often:');
        lines.push('');
        for (const p of coupledPairs.slice(0, 5)) {
            lines.push('- ' + path.basename(p.fileA) + ' <-> ' + path.basename(p.fileB) + ' - ' + (p.strength * 100).toFixed(0) + '% co-change rate');
        }
        lines.push('');
    }

    // Blast radius section
    if (maxBlastCommit) {
        lines.push('## Commit Impact Analysis');
        lines.push('Average blast radius: ' + avgBlast + ' files per commit');
        lines.push('Highest impact commit: ' + (maxBlastCommit.hash || '').slice(0, 7) + ' by ' + (maxBlastCommit.author || 'unknown') + ' - ' + (maxBlastCommit.directCount || 0) + ' files changed, ' + (maxBlastCommit.transitiveCount || 0) + ' downstream impacted');
        if (maxBlastCommit.message) {
            lines.push('> "' + maxBlastCommit.message + '"');
        }
        lines.push('');
    }

    // Core modules
    lines.push('## Core Modules (Most Referenced)');
    for (const m of coreModules) { lines.push('- ' + m.name + ' - ' + m.reason); }
    lines.push('');

    // Entry points
    lines.push('## Entry Points');
    if (entryPoints.length > 0) {
        for (const ep of entryPoints) { lines.push('- ' + ep); }
    } else {
        lines.push('_No entry points detected_');
    }
    lines.push('');

    // Dependencies
    lines.push('## Dependencies');
    lines.push('- Internal imports: ' + (graph.stats.edgesByType['imports'] || 0) + ' edges');
    lines.push('- External packages: ' + externalDeps.length + ' (' + externalDeps.slice(0, 10).join(', ') + (externalDeps.length > 10 ? '...' : '') + ')');
    lines.push('');

    // Graph
    lines.push('## Knowledge Graph');
    lines.push('- ' + graph.stats.totalNodes + ' nodes (' + Object.entries(graph.stats.nodesByType).map(([k, v]) => v + ' ' + k + 's').join(', ') + ')');
    lines.push('- ' + graph.stats.totalEdges + ' edges (' + Object.entries(graph.stats.edgesByType).map(([k, v]) => v + ' ' + k).join(', ') + ')');

    const markdownReport = lines.join('\n');

    const summary: ArchitectureSummary = {
        overview,
        languages,
        fileCount,
        entityCount,
        entryPoints,
        coreModules,
        riskHotspots,
        coupledPairs,
        busFactor,
        dependencies: {
            internal: graph.stats.edgesByType['imports'] || 0,
            external: externalDeps.length,
        },
        markdownReport,
    };

    const jsonPath = path.join(analysisDir, 'summary.json');
    fs.writeFileSync(jsonPath, JSON.stringify(summary, null, 2));

    const mdPath = path.join(analysisDir, 'architecture_summary.md');
    fs.writeFileSync(mdPath, markdownReport);

    console.log('AIL L4-CP2 | Architecture summary generated (' + markdownReport.length + ' chars)');
    return summary;
}
